language: ruby
rvm:
- 2.4.2
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
before_script: bundle exec puppet --version
script:
- bundle exec rake tests
env:
- PUPPET_VERSION='~> 4.3.0'
